---
title: "Plant Species Diversity"
author: NULL
date: NULL
output:
  pdf_document: default
  word_document: default
header-includes:
 - \usepackage[width=\textwidth]{caption}
always_allow_html: yes
csl: ../citations/citations/apa.csl
bibliography: ../citations/citations/citations.bib
link-citations: yes
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F)
knitr::opts_chunk$set(dpi = 300) 
knitr::opts_chunk$set(message = F)
knitr::opts_chunk$set(warning = F)
```

Information on production at Ecological Sites implies some superficial, yet essential, components of plant diversity. 

### run analyses for both LPI and SR, most of these things are pretty much dirt common and should be found on lines without much hassle !?

```{r paths and files}
praw <- '../data/raw'
ppro <- '../data/processed'
f <- list.files(praw, pattern = 'csv')
fp <- list.files(ppro, pattern = 'csv')
```

```{r Import Data for both Species Richness and LPI, eval = F}

aim_rich <- read.csv(file.path(ppro, fp[grep('AIM_Rich', fp)]))

aim_lpi <- read.csv(file.path(ppro, fp[grep('AIM_LPI', fp)]))

esds <- read.csv(file.path(praw, f[grep('Plot.*ESD', f)])) %>% drop_na()

# aim_data <-  # CREATE BOOLEAN COLUMN, 1 = ON LPI, 0 - MISSING FROM LPI - 

```

```{r Lookup Grass and Shrub Status}

photosynthetic <- read.csv(file.path(praw, f[grep('Photo', f)])) %>% 
  rename(SYMBOL = USDA.Species.Code, PHOTOSYNTHETIC = Photosynthetic.Group) %>% 
  mutate(PHOTOSYNTHETIC = if_else(str_detect(PHOTOSYNTHETIC, 'C3'), 'PG-C3', 'PG-C4' )) 

# %>%  
  #left_join(, photosynthetic, by = 'SYMBOL')

rm(f, praw, photosynthetic)
```

```{r Lookup Nativity status, eval = F}

nativity <- read.csv(file.path(ppro, fp[grep('Native', fp)]))

# %>%  
  #left_join(, photosynthetic, by = 'SYMBOL')

rm(nativity)
```


```{r Filter Reference Datasets}

richness <- read.csv(file.path(praw, f[grep('Associations', f)])) %>% 
  filter(PHASE == '1.1', str_length(SYMBOL) >= 4)  

# this where production > 0 - represents expected richness for a site
production_zero <- richness %>% 
  filter(LOWER > 0) %>% 
  group_by(ECO.SITE, STATE, FUNCTIONAL) %>% 
  count()   

production <- richness %>% # this with 0 production - 
  # represents all core gamma richness by ESD ??
  group_by(ECO.SITE, STATE, FUNCTIONAL) %>% 
  count()


# How many plots meet A for each standard ? And where do they sit relative to B ?

# Let us split out Grass, into C3, C4, and annual - three categories
# perhaps also split out Shrub into (resprout) and (non-resprout) / or narrow leaf / broadleaf


# let us split out forbs into native and non-native
# Create a facet wrap of each major functional group
# - Shrub (resprout), Shrub (non-resprout),  - and then colour by ESD group.

# so cols = TREE, SHRUB (NS), SHRUB (S), PG - C3, PG - C4, AG, PERENNIAL FORB, ANNUAL FORB,   

```


```{r Join Homebrewed ESD groups to Ecological Site Descriptions}

esdM <- read.csv(file.path(praw, f[grep('modules', f)]))

```


```{r Boxplots of different ESG with ESDs and reference standards}

cols <- qualitative_hcl(9, palette = "Dark 3") # these for matching with the species diversity. 

```


```{r clean environment}

```



# References


